### ISSUE TITLE
Pin connection difference between PCIe0 and PCIe1

### ISSUE THREAD

**Issue by xcancerberox** [LibreRouterOrg/board#37]
The 37th pin on PCIe1 is connected to ground but not on PCIe0.

Accordingly to PCIe M2 mSATA pinout, the pin must be connected to GND. But is reserved on PCIe minicard pinout. So, one of the two is wrong.

![image](https://user-images.githubusercontent.com/1068399/62949209-2b54f480-bdbc-11e9-9ac7-9f7540a3c57c.png)

Proposal: Add 0Ohm resistor to ground in both cases and test.

**Comment by spiccinini** [comment]
In our 802.11an WLAN mPCI cards that are used with the LR the pin 37 is not connected to anything.

I think that the most compatible option is to leave both pci connector's pin 37 not connected to anything. Because if the mpci board wants GND in this pin, there are many pins for that so leaving floating will work. And for other mPCI boards that use pin 37 for other things, it will not short circuit it to GND
